version: '3.2'

services:
  mysql:
    build:
      context: mysql/
      args:
        VERSION: 5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - test
  mysqlsetup:
    image: data_storages_mysql
    volumes:
      - type: bind
        source: ./mysql/data/users.sql
        target: /data/users.sql
        read_only: true
    depends_on:
      - mysql
    restart: "no"
    command: sh -c "sleep 15 && mysql -hmysql -uuser -ppw my_db < /data/users.sql"


  elasticsearch:
    build:
      context: elasticsearch/
      args:
        VERSION: 7.9.1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: password
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - test

  logstash:
    build:
      context: logstash/
      args:
        VERSION: 7.9.1
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/lib/mysql-connector-java-8.0.18.jar
        target: /usr/share/logstash/lib/mysql-connector-java-8.0.18.jar
        read_only: true
      - type: bind
        source: ./logstash/template
        target: /usr/share/logstash/template
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - test
    depends_on:
      - elasticsearch

networks:
  test:
    driver: bridge