@startuml

/' SearchProduct
 - Core Domain
'/
abstract Search<<Core>> {
    + policy: ISearchPolicy
    + serviceProvider: IQueryServiceProvider
    - translator: ConditionTranslator
    - queryWorker: SearchQueryWorker

    + abstract getType() -> SearchColumnType
    + query(ISearchCondition) -> SearchAnswer<T>
}

/' ISearchCondition
 - 검색 도메인 가시화
 - 검색 조건 정의
 - 버전 관리
'/
interface ISearchCondition {
    + columns() -> ISearchColumn<?>[]
    + requiredColumns() -> ColumnTypeGroup[]
    + getPageable() -> Pageable
}

class ColumnTypeGroup {
    + types: ColumnType[]
}

interface ISearchColumn<T> {
    + type() -> ColumnType
    + rawValue() -> T
    + operator() -> SearchOperator
    + readableQueryApis() -> QueryApiType[]
}

enum ColumnType {
    { customized }
}

enum SearchOperator {
    : AND
    : OR
}

class SearchAnswer<T> {
    + conditions: ISearchCondition
    + values: Page<SearchAnswerItem<T>>
}

class SearchAnswerItem<T> {
    + identifier: T
    + idType: SearchColumnType
    + references: Map<SearchColumnType, Object>
}


/' ConditionTranslator

validation
 - 필수 값 검사, 실패시 예외 InvalidConditionException.
 - QueryAPIProvider 지원 여부 검사, 실패시 예외 InvalidConditionException.

translation by ISearchPolicy
 1. Or/And 그룹화.
 2. PriorityQueryByColumn

'/

class ConditionTranslator {
    + translate(ISearchPolicy, ISearchCondition) \n  -> QueryCoordinator[]
}

class InvalidConditionException


/' ISearchPolicyProvider
'/
interface ISearchPolicy {
    + prioritiesQueryByColumn: [PriorityQueryByColumn]
}

class PriorityQueryByColumn {
    + ColumnType: ColumnType
    + priorityQueryType: PriorityQueryType
    + queryServiceType: QueryServiceType
}

enum PriorityQueryType {
: ALWAYS // 항상사용
: PREFER // 우선사용
: AVOID // 회피
}


class QueryWorkerException

/' SearchQueryWorker
'/
class SearchQueryWorker {
    + <T> waterfall(QueryServiceType, QueryCoordinator[]) -> List<SearchAnswerItem<T>>
    + <T> blockPage(QueryServiceType, QueryCoordinator[]) -> Page<SearchAnswerItem<T>>
}

/' QueryCoordinator
'/
abstract QueryCoordinator {
    # conditions: ISearchColumn<?>[]
    # references: ColumnType[]
    # pageable: Pageable
    + isStandard: boolean
    + infraType() -> QueryServiceType
    + query(SearchInfraInterface) -> List<SearchResultItem<?>>
}

/' IQueryService
 - 기본 순서는 IQueryServiceProvider 에 정의된 순서.
'/
interface IQueryService<T> {
    + type() -> QueryServiceType
    + search(ISearchColumn<?>[], Pageable) -> Page<T>
    + identifier() -> ColumnType
    + references() -> ColumnType[]
}

interface IQueryServiceProvider {
    + access(QueryServiceType) -> IQueryService
    + defaultPriority() -> QueryServiceType[]
}

enum QueryServiceType {
{ customized }
}


Search .> SearchAnswer
Search *-- SearchQueryWorker
Search *-- ConditionTranslator
Search o--- IQueryServiceProvider
Search o--- ISearchPolicy

ISearchCondition "1" -- "0.." ISearchColumn
ISearchCondition <. Search
ISearchCondition .> ColumnTypeGroup

ISearchColumn . ColumnType
ISearchColumn .. SearchOperator

ColumnTypeGroup ..> ColumnType

IQueryServiceProvider "1" ..> "0.." IQueryService

IQueryService . QueryServiceType

ISearchPolicy ..> PriorityQueryByColumn

PriorityQueryByColumn ..> PriorityQueryType

ConditionTranslator ..> ISearchPolicy

SearchQueryWorker ..> IQueryServiceProvider
SearchQueryWorker . QueryWorkerException

QueryCoordinator <.. SearchQueryWorker

ConditionTranslator ..> QueryCoordinator
ConditionTranslator . InvalidConditionException

SearchAnswer "1" -- "0.." SearchAnswerItem

@enduml